// Code generated by protoc-gen-gopherd. DO NOT EDIT.
// source: proto/testdata/testdata.proto
package testdata

import registry "github.com/gopherd/doge/proto"

const (
	TestdataType = 99999999
)

func init() {
	registry.Register("testdata", TestdataType, func() registry.Message { return new(Testdata) })
}

func (*Testdata) Type() registry.Type { return TestdataType }
